/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ISynchronizationBotLensInterface extends Interface {
  getFunction(
    nameOrSignature: "swapAndAddLiquidity" | "swapAndRemoveLiquidity"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "swapAndAddLiquidity",
    values: [
      AddressLike,
      AddressLike[],
      BigNumberish,
      AddressLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndRemoveLiquidity",
    values: [
      AddressLike,
      AddressLike[],
      BigNumberish,
      AddressLike[],
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "swapAndAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndRemoveLiquidity",
    data: BytesLike
  ): Result;
}

export interface ISynchronizationBotLens extends BaseContract {
  connect(runner?: ContractRunner | null): ISynchronizationBotLens;
  waitForDeployment(): Promise<this>;

  interface: ISynchronizationBotLensInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  swapAndAddLiquidity: TypedContractMethod<
    [
      _uniswapV2Router02: AddressLike,
      _swapPath: AddressLike[],
      _swapAmount: BigNumberish,
      _liquidityPath: AddressLike[],
      _liquidityAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  swapAndRemoveLiquidity: TypedContractMethod<
    [
      _uniswapV2Router02: AddressLike,
      _swapPath: AddressLike[],
      _swapAmount: BigNumberish,
      _liquidityPath: AddressLike[],
      _liquidityK: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "swapAndAddLiquidity"
  ): TypedContractMethod<
    [
      _uniswapV2Router02: AddressLike,
      _swapPath: AddressLike[],
      _swapAmount: BigNumberish,
      _liquidityPath: AddressLike[],
      _liquidityAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapAndRemoveLiquidity"
  ): TypedContractMethod<
    [
      _uniswapV2Router02: AddressLike,
      _swapPath: AddressLike[],
      _swapAmount: BigNumberish,
      _liquidityPath: AddressLike[],
      _liquidityK: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
