/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUniswapV2LPOracle } from "./IUniswapV2LPOracle";
export type { UniswapV2LPOracle } from "./UniswapV2LPOracle";
