/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LimitPriceCOMInterface extends ethers.utils.Interface {
  functions: {
    "canBeFilledAfterSwap((address,address,address,uint256,address,uint256,address,uint256,uint256,uint256,bool,uint256,uint256,bytes),bytes,bytes,uint256)": FunctionFragment;
    "getLimitPrice(bytes)": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "keeperRewardDistributor()": FunctionFragment;
    "pm()": FunctionFragment;
    "priceOracle()": FunctionFragment;
    "primexDNS()": FunctionFragment;
    "registry()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canBeFilledAfterSwap",
    values: [
      {
        bucket: string;
        positionAsset: string;
        depositAsset: string;
        depositAmount: BigNumberish;
        feeToken: string;
        protocolFee: BigNumberish;
        trader: string;
        deadline: BigNumberish;
        id: BigNumberish;
        leverage: BigNumberish;
        shouldOpenPosition: boolean;
        createdAt: BigNumberish;
        updatedConditionsAt: BigNumberish;
        extraParams: BytesLike;
      },
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLimitPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "keeperRewardDistributor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "primexDNS", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "canBeFilledAfterSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLimitPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "keeperRewardDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "primexDNS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export class LimitPriceCOM extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LimitPriceCOMInterface;

  functions: {
    canBeFilledAfterSwap(
      arg0: {
        bucket: string;
        positionAsset: string;
        depositAsset: string;
        depositAmount: BigNumberish;
        feeToken: string;
        protocolFee: BigNumberish;
        trader: string;
        deadline: BigNumberish;
        id: BigNumberish;
        leverage: BigNumberish;
        shouldOpenPosition: boolean;
        createdAt: BigNumberish;
        updatedConditionsAt: BigNumberish;
        extraParams: BytesLike;
      },
      _params: BytesLike,
      arg2: BytesLike,
      _exchangeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getLimitPrice(
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialize(
      _primexDNS: string,
      _priceOracle: string,
      _pm: string,
      _keeperRewardDistributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    keeperRewardDistributor(overrides?: CallOverrides): Promise<[string]>;

    pm(overrides?: CallOverrides): Promise<[string]>;

    priceOracle(overrides?: CallOverrides): Promise<[string]>;

    primexDNS(overrides?: CallOverrides): Promise<[string]>;

    registry(overrides?: CallOverrides): Promise<[string]>;

    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  canBeFilledAfterSwap(
    arg0: {
      bucket: string;
      positionAsset: string;
      depositAsset: string;
      depositAmount: BigNumberish;
      feeToken: string;
      protocolFee: BigNumberish;
      trader: string;
      deadline: BigNumberish;
      id: BigNumberish;
      leverage: BigNumberish;
      shouldOpenPosition: boolean;
      createdAt: BigNumberish;
      updatedConditionsAt: BigNumberish;
      extraParams: BytesLike;
    },
    _params: BytesLike,
    arg2: BytesLike,
    _exchangeRate: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getLimitPrice(
    _params: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialize(
    _primexDNS: string,
    _priceOracle: string,
    _pm: string,
    _keeperRewardDistributor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  keeperRewardDistributor(overrides?: CallOverrides): Promise<string>;

  pm(overrides?: CallOverrides): Promise<string>;

  priceOracle(overrides?: CallOverrides): Promise<string>;

  primexDNS(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    _interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    canBeFilledAfterSwap(
      arg0: {
        bucket: string;
        positionAsset: string;
        depositAsset: string;
        depositAmount: BigNumberish;
        feeToken: string;
        protocolFee: BigNumberish;
        trader: string;
        deadline: BigNumberish;
        id: BigNumberish;
        leverage: BigNumberish;
        shouldOpenPosition: boolean;
        createdAt: BigNumberish;
        updatedConditionsAt: BigNumberish;
        extraParams: BytesLike;
      },
      _params: BytesLike,
      arg2: BytesLike,
      _exchangeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getLimitPrice(
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _primexDNS: string,
      _priceOracle: string,
      _pm: string,
      _keeperRewardDistributor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    keeperRewardDistributor(overrides?: CallOverrides): Promise<string>;

    pm(overrides?: CallOverrides): Promise<string>;

    priceOracle(overrides?: CallOverrides): Promise<string>;

    primexDNS(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;
  };

  estimateGas: {
    canBeFilledAfterSwap(
      arg0: {
        bucket: string;
        positionAsset: string;
        depositAsset: string;
        depositAmount: BigNumberish;
        feeToken: string;
        protocolFee: BigNumberish;
        trader: string;
        deadline: BigNumberish;
        id: BigNumberish;
        leverage: BigNumberish;
        shouldOpenPosition: boolean;
        createdAt: BigNumberish;
        updatedConditionsAt: BigNumberish;
        extraParams: BytesLike;
      },
      _params: BytesLike,
      arg2: BytesLike,
      _exchangeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLimitPrice(
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _primexDNS: string,
      _priceOracle: string,
      _pm: string,
      _keeperRewardDistributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    keeperRewardDistributor(overrides?: CallOverrides): Promise<BigNumber>;

    pm(overrides?: CallOverrides): Promise<BigNumber>;

    priceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    primexDNS(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canBeFilledAfterSwap(
      arg0: {
        bucket: string;
        positionAsset: string;
        depositAsset: string;
        depositAmount: BigNumberish;
        feeToken: string;
        protocolFee: BigNumberish;
        trader: string;
        deadline: BigNumberish;
        id: BigNumberish;
        leverage: BigNumberish;
        shouldOpenPosition: boolean;
        createdAt: BigNumberish;
        updatedConditionsAt: BigNumberish;
        extraParams: BytesLike;
      },
      _params: BytesLike,
      arg2: BytesLike,
      _exchangeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLimitPrice(
      _params: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _primexDNS: string,
      _priceOracle: string,
      _pm: string,
      _keeperRewardDistributor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    keeperRewardDistributor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    primexDNS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
