/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBucketStorageV2,
  IBucketStorageV2Interface,
} from "../IBucketStorageV2";

const _abi = [
  {
    inputs: [],
    name: "bucketExtension",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBucketStorageV2__factory {
  static readonly abi = _abi;
  static createInterface(): IBucketStorageV2Interface {
    return new utils.Interface(_abi) as IBucketStorageV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBucketStorageV2 {
    return new Contract(address, _abi, signerOrProvider) as IBucketStorageV2;
  }
}
