/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEPMXPriceFeed,
  IEPMXPriceFeedInterface,
} from "../IEPMXPriceFeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
    ],
    name: "setAnswer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEPMXPriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IEPMXPriceFeedInterface {
    return new utils.Interface(_abi) as IEPMXPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEPMXPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as IEPMXPriceFeed;
  }
}
