/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICurveReentrencyWrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim_admin_fees"
      | "remove_liquidity(uint256,uint256[2])"
      | "remove_liquidity(uint256,uint256[4])"
      | "remove_liquidity(uint256,uint256[3])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claim_admin_fees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[2])",
    values: [BigNumberish, [BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[4])",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "remove_liquidity(uint256,uint256[3])",
    values: [BigNumberish, [BigNumberish, BigNumberish, BigNumberish]]
  ): string;

  decodeFunctionResult(
    functionFragment: "claim_admin_fees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[2])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[4])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remove_liquidity(uint256,uint256[3])",
    data: BytesLike
  ): Result;
}

export interface ICurveReentrencyWrapper extends BaseContract {
  connect(runner?: ContractRunner | null): ICurveReentrencyWrapper;
  waitForDeployment(): Promise<this>;

  interface: ICurveReentrencyWrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim_admin_fees: TypedContractMethod<[], [void], "view">;

  "remove_liquidity(uint256,uint256[2])": TypedContractMethod<
    [tokenAmount: BigNumberish, amounts: [BigNumberish, BigNumberish]],
    [void],
    "view"
  >;

  "remove_liquidity(uint256,uint256[4])": TypedContractMethod<
    [
      tokenAmount: BigNumberish,
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "view"
  >;

  "remove_liquidity(uint256,uint256[3])": TypedContractMethod<
    [
      tokenAmount: BigNumberish,
      amounts: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim_admin_fees"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[2])"
  ): TypedContractMethod<
    [tokenAmount: BigNumberish, amounts: [BigNumberish, BigNumberish]],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[4])"
  ): TypedContractMethod<
    [
      tokenAmount: BigNumberish,
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "remove_liquidity(uint256,uint256[3])"
  ): TypedContractMethod<
    [
      tokenAmount: BigNumberish,
      amounts: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "view"
  >;

  filters: {};
}
