/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IActivityRewardDistributor {
  export type BucketWithRoleStruct = {
    bucketAddress: AddressLike;
    role: BigNumberish;
  };

  export type BucketWithRoleStructOutput = [
    bucketAddress: string,
    role: bigint
  ] & { bucketAddress: string; role: bigint };
}

export declare namespace IActivityRewardDistributorStorage {
  export type UserInfoStruct = {
    fixedReward: BigNumberish;
    lastUpdatedRewardIndex: BigNumberish;
    oldBalance: BigNumberish;
  };

  export type UserInfoStructOutput = [
    fixedReward: bigint,
    lastUpdatedRewardIndex: bigint,
    oldBalance: bigint
  ] & {
    fixedReward: bigint;
    lastUpdatedRewardIndex: bigint;
    oldBalance: bigint;
  };
}

export interface IActivityRewardDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimReward"
      | "decreaseRewardPerDay"
      | "dns"
      | "getBucketAccumulatedReward"
      | "getClaimableReward"
      | "getUserInfoFromBucket"
      | "initialize"
      | "pause"
      | "pmx"
      | "registry"
      | "setupBucket"
      | "traderBalanceVault"
      | "treasury"
      | "unpause"
      | "updateUserActivity"
      | "updateUsersActivities"
      | "withdrawPmx"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ClaimReward"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [IActivityRewardDistributor.BucketWithRoleStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseRewardPerDay",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dns", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBucketAccumulatedReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableReward",
    values: [IActivityRewardDistributor.BucketWithRoleStruct[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfoFromBucket",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "pmx", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setupBucket",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "traderBalanceVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateUserActivity",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUsersActivities",
    values: [
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPmx",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseRewardPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBucketAccumulatedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfoFromBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pmx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setupBucket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "traderBalanceVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateUserActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUsersActivities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPmx",
    data: BytesLike
  ): Result;
}

export namespace ClaimRewardEvent {
  export type InputTuple = [
    user: AddressLike,
    bucket: AddressLike,
    role: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    bucket: string,
    role: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    bucket: string;
    role: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IActivityRewardDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IActivityRewardDistributor;
  waitForDeployment(): Promise<this>;

  interface: IActivityRewardDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimReward: TypedContractMethod<
    [bucketsArray: IActivityRewardDistributor.BucketWithRoleStruct[]],
    [void],
    "nonpayable"
  >;

  decreaseRewardPerDay: TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, rewardPerDay: BigNumberish],
    [void],
    "nonpayable"
  >;

  dns: TypedContractMethod<[], [string], "nonpayable">;

  getBucketAccumulatedReward: TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish],
    [bigint],
    "view"
  >;

  getClaimableReward: TypedContractMethod<
    [
      bucketsArray: IActivityRewardDistributor.BucketWithRoleStruct[],
      user: AddressLike
    ],
    [bigint],
    "view"
  >;

  getUserInfoFromBucket: TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, user: AddressLike],
    [IActivityRewardDistributorStorage.UserInfoStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _pmx: AddressLike,
      _dns: AddressLike,
      _registry: AddressLike,
      _treasury: AddressLike,
      _traderBalanceVault: AddressLike,
      _whiteBlackList: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pmx: TypedContractMethod<[], [string], "nonpayable">;

  registry: TypedContractMethod<[], [string], "nonpayable">;

  setupBucket: TypedContractMethod<
    [
      bucket: AddressLike,
      role: BigNumberish,
      increaseAmount: BigNumberish,
      rewardPerDay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  traderBalanceVault: TypedContractMethod<[], [string], "nonpayable">;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateUserActivity: TypedContractMethod<
    [
      bucket: AddressLike,
      user: AddressLike,
      newBalance: BigNumberish,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateUsersActivities: TypedContractMethod<
    [
      bucket: AddressLike,
      users: AddressLike[],
      newBalances: BigNumberish[],
      length: BigNumberish,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdrawPmx: TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<
    [bucketsArray: IActivityRewardDistributor.BucketWithRoleStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decreaseRewardPerDay"
  ): TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, rewardPerDay: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dns"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getBucketAccumulatedReward"
  ): TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimableReward"
  ): TypedContractMethod<
    [
      bucketsArray: IActivityRewardDistributor.BucketWithRoleStruct[],
      user: AddressLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInfoFromBucket"
  ): TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, user: AddressLike],
    [IActivityRewardDistributorStorage.UserInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _pmx: AddressLike,
      _dns: AddressLike,
      _registry: AddressLike,
      _treasury: AddressLike,
      _traderBalanceVault: AddressLike,
      _whiteBlackList: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pmx"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "setupBucket"
  ): TypedContractMethod<
    [
      bucket: AddressLike,
      role: BigNumberish,
      increaseAmount: BigNumberish,
      rewardPerDay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "traderBalanceVault"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateUserActivity"
  ): TypedContractMethod<
    [
      bucket: AddressLike,
      user: AddressLike,
      newBalance: BigNumberish,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUsersActivities"
  ): TypedContractMethod<
    [
      bucket: AddressLike,
      users: AddressLike[],
      newBalances: BigNumberish[],
      length: BigNumberish,
      role: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawPmx"
  ): TypedContractMethod<
    [bucket: AddressLike, role: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimReward"
  ): TypedContractEvent<
    ClaimRewardEvent.InputTuple,
    ClaimRewardEvent.OutputTuple,
    ClaimRewardEvent.OutputObject
  >;

  filters: {
    "ClaimReward(address,address,uint8,uint256)": TypedContractEvent<
      ClaimRewardEvent.InputTuple,
      ClaimRewardEvent.OutputTuple,
      ClaimRewardEvent.OutputObject
    >;
    ClaimReward: TypedContractEvent<
      ClaimRewardEvent.InputTuple,
      ClaimRewardEvent.OutputTuple,
      ClaimRewardEvent.OutputObject
    >;
  };
}
