/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DepositManagerStorage__factory } from "./DepositManagerStorage__factory";
export { DepositManagerStorageV2__factory } from "./DepositManagerStorageV2__factory";
